# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # CreateMediaRequestLanguageCode - Language codes are concise, standardized symbols that denote languages, utilizing either two or three characters for identification. The language code must be compliant with the BCP 47 standard to ensure compatibility. (for text only).
      # 
      class CreateMediaRequestLanguageCode < T::Enum
        enums do
          EN = new('en')
          IT = new('it')
          PL = new('pl')
          ES = new('es')
          FR = new('fr')
          RU = new('ru')
          NL = new('nl')
        end
      end
    end
  end
end
