# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # CreateMediaRequestDomainsDefaultPolicy - Specifies the default access policy for domains. 
      # If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` lists. 
      # If set to `deny`, all domains are denied access unless otherwise specified in the `allow` lists.
      # 
      class CreateMediaRequestDomainsDefaultPolicy < T::Enum
        enums do
          ALLOW = new('allow')
          DENY = new('deny')
        end
      end
    end
  end
end
