# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # CreateMediaRequestUserAgentsDefaultPolicy - Specifies the default access policy for user agents (browsers, bots, etc.).
      # If set to `allow`, all user agents are allowed access unless otherwise specified in the `deny` lists. 
      # If set to `deny`, all user agents are denied access unless otherwise specified in the `allow` lists.
      # 
      class CreateMediaRequestUserAgentsDefaultPolicy < T::Enum
        enums do
          ALLOW = new('allow')
          DENY = new('deny')
        end
      end
    end
  end
end
