# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # CreateLiveStreamRequestMaxResolution - Max resolution can be used to control the maximum resolution your media is encoded, stored, and streamed at.
      class CreateLiveStreamRequestMaxResolution < T::Enum
        enums do
          ONE_THOUSAND_AND_EIGHTYP = new('1080p')
          SEVEN_HUNDRED_AND_TWENTYP = new('720p')
          FOUR_HUNDRED_AND_EIGHTYP = new('480p')
        end
      end
    end
  end
end
