
# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # Displays the result of the request.
      class CreateSigningKeyResponseDTO
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier is generated by FastPix for the signing keys.
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('id') } }
        # A private key is a byte encoded secret key used to create a signed JSON Web Token (JWT) for authentication.
        field :private_key, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('privateKey') } }
        # Time the media was generated, defined as a localDateTime (UTC Time).
        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('createdAt'), 'decoder': Utils.datetime_from_iso_format(true) } }

        sig { params(id: T.nilable(::String), private_key: T.nilable(::String), created_at: T.nilable(::DateTime)).void }
        def initialize(id: nil, private_key: nil, created_at: nil)
          @id = id
          @private_key = private_key
          @created_at = created_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @private_key == other.private_key
          return false unless @created_at == other.created_at
          true
        end
      end
    end
  end
end
