# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # CreateMediaRequestMp4Support - “capped_4k": Generates an mp4 video file up to 4k resolution "audioOnly": Generates an m4a audio file of the media file "audioOnly,capped_4k": Generates both video and audio media files for offline viewing
      # 
      class CreateMediaRequestMp4Support < T::Enum
        enums do
          CAPPED_4K = new('capped_4k')
          AUDIO_ONLY = new('audioOnly')
          AUDIO_ONLY_CAPPED_4K = new('audioOnly,capped_4k')
        end
      end
    end
  end
end
