
# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    

      class GetAllSigningKeyResponseDTO
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier is generated by FastPix for the signing keys.
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('id') } }
        # Time the media was generated, defined as a localDateTime (UTC Time).
        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('createdAt'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # It display a specific setup where all operations are conducted.
        field :workspace, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::SigningKeyWorkspaceDTO)), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('workspace') } }
        # Pagination organizes content into pages for better readability and navigation.
        field :pagination, Crystalline::Nilable.new(Models::Components::SingingKeysPagination), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('pagination') } }

        sig { params(id: T.nilable(::String), created_at: T.nilable(::DateTime), workspace: T.nilable(T::Array[Models::Components::SigningKeyWorkspaceDTO]), pagination: T.nilable(Models::Components::SingingKeysPagination)).void }
        def initialize(id: nil, created_at: nil, workspace: nil, pagination: nil)
          @id = id
          @created_at = created_at
          @workspace = workspace
          @pagination = pagination
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @created_at == other.created_at
          return false unless @workspace == other.workspace
          return false unless @pagination == other.pagination
          true
        end
      end
    end
  end
end
