# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # This object contains the livestream playback response details for SRT Protocol.
      class GetCreateLiveStreamResponseDTOSrtPlaybackResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier for the SRT playback stream. This ID is used to distinguish between different playback streams.
        field :srt_playback_stream_id, T.nilable(::String), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('srtPlaybackStreamId') } }
        # A playback secret used for securing the SRT playback stream. This ensures that only authorized users can access the playback.
        field :srt_playback_secret, T.nilable(::String), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('srtPlaybackSecret') } }

        sig { params(srt_playback_stream_id: T.nilable(::String), srt_playback_secret: T.nilable(::String)).void }
        def initialize(srt_playback_stream_id: nil, srt_playback_secret: nil)
          @srt_playback_stream_id = srt_playback_stream_id
          @srt_playback_secret = srt_playback_secret
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @srt_playback_stream_id == other.srt_playback_stream_id
          return false unless @srt_playback_secret == other.srt_playback_secret
          true
        end
      end
    end
  end
end
