# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # Displays the result of the input Media settings.
      class InputMediaSettings
        extend T::Sig
        include Crystalline::MetadataFields

        # You can search for videos with specific key value pairs using metadata, when you tag a video in "key":"value"s pairs. Dynamic Metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
        field :metadata, T.nilable(Models::Components::CreateLiveStreamRequestMetadata), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('metadata') } }
        # Max resolution can be used to control the maximum resolution your media is encoded, stored, and streamed at.
        field :max_resolution, T.nilable(Models::Components::CreateLiveStreamRequestMaxResolution), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('maxResolution'), 'decoder': Utils.enum_from_string(Models::Components::CreateLiveStreamRequestMaxResolution, true) } }
        # In case the software streaming the live, get disrupted for any reason and get disconnect from FastPix, the reconnect window specifies the waiting time span of FastPix will wait before ending the stream. Before starting the stream, you can set the reconnect window time set which is up to 1800 seconds.
        field :reconnect_window, T.nilable(::Integer), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('reconnectWindow') } }
        # Determines whether the recorded stream should be publicly accessible or private in Live to VOD (Video on Demand).
        field :media_policy, T.nilable(Models::Components::MediaPolicy), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('mediaPolicy'), 'decoder': Utils.enum_from_string(Models::Components::MediaPolicy, true) } }

        sig { params(metadata: T.nilable(Models::Components::CreateLiveStreamRequestMetadata), max_resolution: T.nilable(Models::Components::CreateLiveStreamRequestMaxResolution), reconnect_window: T.nilable(::Integer), media_policy: T.nilable(Models::Components::MediaPolicy)).void }
        def initialize(metadata: nil, max_resolution: Models::Components::CreateLiveStreamRequestMaxResolution::ONE_THOUSAND_AND_EIGHTYP, reconnect_window: 60, media_policy: Models::Components::MediaPolicy::PUBLIC)
          @metadata = metadata
          @max_resolution = max_resolution
          @reconnect_window = reconnect_window
          @media_policy = media_policy
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @metadata == other.metadata
          return false unless @max_resolution == other.max_resolution
          return false unless @reconnect_window == other.reconnect_window
          return false unless @media_policy == other.media_policy
          true
        end
      end
    end
  end
end
