# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    

      class PatchLiveStreamRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # You can search for videos with specific key value pairs using metadata, when you tag a video in "key":"value"s pairs. Dynamic Metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
        field :metadata, T.nilable(Models::Components::PatchLiveStreamRequestMetadata), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('metadata') } }
        # In case the software streaming the live, get disrupted for any reason and get disconnect from FastPix, the reconnect window specifies the waiting time span of FastPix will wait before ending the stream. Before starting the stream, you can set the reconnect window time set which is up to 1800 seconds.
        field :reconnect_window, T.nilable(::Integer), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('reconnectWindow') } }

        sig { params(metadata: T.nilable(Models::Components::PatchLiveStreamRequestMetadata), reconnect_window: T.nilable(::Integer)).void }
        def initialize(metadata: nil, reconnect_window: 60)
          @metadata = metadata
          @reconnect_window = reconnect_window
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @metadata == other.metadata
          return false unless @reconnect_window == other.reconnect_window
          true
        end
      end
    end
  end
end
