# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # Displays the result of the playback settings.
      class PlaybackSettings
        extend T::Sig
        include Crystalline::MetadataFields

        # Determines if access to the streamed content is kept private or available to all.
        field :access_policy, T.nilable(Models::Components::PlaybackSettingsAccessPolicy), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('accessPolicy'), 'decoder': Utils.enum_from_string(Models::Components::PlaybackSettingsAccessPolicy, true) } }

        sig { params(access_policy: T.nilable(Models::Components::PlaybackSettingsAccessPolicy)).void }
        def initialize(access_policy: Models::Components::PlaybackSettingsAccessPolicy::PUBLIC)
          @access_policy = access_policy
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @access_policy == other.access_policy
          true
        end
      end
    end
  end
end
