# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # Restrictions based on the originating domain of a request (e.g., whether requests from certain websites should be allowed or blocked).
      class PlaybackIdDomains
        extend T::Sig
        include Crystalline::MetadataFields

        # This sets the default behavior for domain access (either "allow" or "deny").
        field :default_policy, T.nilable(Models::Components::PlaybackIdDomainsDefaultPolicy), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('defaultPolicy'), 'decoder': Utils.enum_from_string(Models::Components::PlaybackIdDomainsDefaultPolicy, true) } }
        # A list of domains that are explicitly allowed access.
        field :allow, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('allow') } }
        # A list of domains that are explicitly blocked from accessing the resource.
        field :deny, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('deny') } }

        sig { params(default_policy: T.nilable(Models::Components::PlaybackIdDomainsDefaultPolicy), allow: T.nilable(T::Array[::String]), deny: T.nilable(T::Array[::String])).void }
        def initialize(default_policy: nil, allow: nil, deny: nil)
          @default_policy = default_policy
          @allow = allow
          @deny = deny
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @default_policy == other.default_policy
          return false unless @allow == other.allow
          return false unless @deny == other.deny
          true
        end
      end
    end
  end
end
