# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    

      class Segment2
        extend T::Sig
        include Crystalline::MetadataFields

        # URL of the segment to be added.
        field :url, ::String, { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('url'), required: true } }
        # Flag indicating the segment should be inserted at the end.
        field :insert_at_end, T::Boolean, { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('insertAtEnd'), required: true } }

        sig { params(url: ::String, insert_at_end: T::Boolean).void }
        def initialize(url:, insert_at_end:)
          @url = url
          @insert_at_end = insert_at_end
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @url == other.url
          return false unless @insert_at_end == other.insert_at_end
          true
        end
      end
    end
  end
end
