# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # SubtitleInputLanguageCode - The BCP 47 language code representing the language of the generated track.
      # 
      class SubtitleInputLanguageCode < T::Enum
        enums do
          AR_SA = new('ar-SA')
          BN_BD = new('bn-BD')
          BN_IN = new('bn-IN')
          CA_ES = new('ca-ES')
          CS_CZ = new('cs-CZ')
          DA_DK = new('da-DK')
          DE_AT = new('de-AT')
          DE_CH = new('de-CH')
          DE_DE = new('de-DE')
          EL_GR = new('el-GR')
          EN_AU = new('en-AU')
          EN_CA = new('en-CA')
          EN_GB = new('en-GB')
          EN_IE = new('en-IE')
          EN_IN = new('en-IN')
          EN_NZ = new('en-NZ')
          EN_US = new('en-US')
          EN_ZA = new('en-ZA')
          ES_AR = new('es-AR')
          ES_CL = new('es-CL')
          ES_CO = new('es-CO')
          ES_ES = new('es-ES')
          ES_MX = new('es-MX')
          ES_US = new('es-US')
          FI_FI = new('fi-FI')
          FR_BE = new('fr-BE')
          FR_CA = new('fr-CA')
          FR_CH = new('fr-CH')
          FR_FR = new('fr-FR')
          HE_IL = new('he-IL')
          HI_IN = new('hi-IN')
          HR_HR = new('hr-HR')
          HU_HU = new('hu-HU')
          ID_ID = new('id-ID')
          IT_CH = new('it-CH')
          IT_IT = new('it-IT')
          JA_JP = new('ja-JP')
          KO_KR = new('ko-KR')
          NL_BE = new('nl-BE')
          NL_NL = new('nl-NL')
          NO_NO = new('no-NO')
          PL_PL = new('pl-PL')
          PT_BR = new('pt-BR')
          PT_PT = new('pt-PT')
          RO_RO = new('ro-RO')
          RU_RU = new('ru-RU')
          SK_SK = new('sk-SK')
          SV_SE = new('sv-SE')
          TA_IN = new('ta-IN')
          TA_LK = new('ta-LK')
          TH_TH = new('th-TH')
          TR_TR = new('tr-TR')
          UK_UA = new('uk-UA')
          BG_BG = new('bg-BG')
          ZH_CN = new('zh-CN')
          ZH_HK = new('zh-HK')
          ZH_TW = new('zh-TW')
        end
      end
    end
  end
end
