# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    

      class Summary
        extend T::Sig
        include Crystalline::MetadataFields

        # Enable or disable the summary feature for the media. Set to true to enable summary or false to disable.
        # 
        field :generate, T::Boolean, { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('generate'), required: true } }
        # Specifies the desired word count for the generated summary. 
        # - The value must be between **30** and **250** words.
        # 
        field :summary_length, T.nilable(::Integer), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('summaryLength') } }

        sig { params(generate: T::Boolean, summary_length: T.nilable(::Integer)).void }
        def initialize(generate:, summary_length: 100)
          @generate = generate
          @summary_length = summary_length
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @generate == other.generate
          return false unless @summary_length == other.summary_length
          true
        end
      end
    end
  end
end
