# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    

      class VideoInput
        extend T::Sig
        include Crystalline::MetadataFields

        # Defines the type of input.
        # 
        field :type, ::String, { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('type'), required: true } }
        # The url hosts the media file for FastPix, which needs to be downloaded to use further. It supports formats like MP3, MP4, MOV, MKV, or TS, and includes text tracks for subtitles/CC (SRT file/VTT file). While FastPix can handle various audio and video formats and codecs, using standard inputs can help with optimal processing speed.
        # 
        field :url, ::String, { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('url'), required: true } }
        # Start time indicates where encoding should begin within the video file. For example, if you want to encode a segment from 3 minutes (180 seconds) to 6 minutes (360 seconds) in a 10-minute (600 seconds) video, the start time is 3 minutes (180 seconds). Note: Start time is always mentioned in seconds.
        # 
        field :start_time, T.nilable(::Float), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('startTime') } }
        # End time indicates where encoding should end within the video file. For example, if you want to encode a segment from 3 minutes (180 seconds) to 6 minutes (360 seconds) in a 10-minute (600 seconds) video, the end time is 6 minutes (360 seconds). Note: End time is always mentioned in seconds.
        # 
        field :end_time, T.nilable(::Float), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('endTime') } }
        # The url of the intro video which is to be added at the start of the video.
        # 
        field :intro_url, T.nilable(::String), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('introUrl') } }
        # The url of the outro video which is to be added at the end of the video.
        # 
        field :outro_url, T.nilable(::String), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('outroUrl') } }
        # The list of the startTime-endTime of the segments to be removed from the actual video.
        # 
        field :expunge_segments, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('expungeSegments') } }
        # A list of media segments to be added or processed. Each segment includes details such as the URL of the media file and instructions on where it should be inserted in the final media composition. A segment can either specify an exact timestamp  (`insertAt`) or indicate that it should be added at the end (`insertAtEnd`).
        field :segments, T.nilable(T::Array[T.any(Models::Components::Segment1, Models::Components::Segment2)]), { 'format_json': { 'letter_case': ::FastpixApiSDK::Utils.field_name('segments') } }

        sig { params(type: ::String, url: ::String, start_time: T.nilable(::Float), end_time: T.nilable(::Float), intro_url: T.nilable(::String), outro_url: T.nilable(::String), expunge_segments: T.nilable(T::Array[::String]), segments: T.nilable(T::Array[T.any(Models::Components::Segment1, Models::Components::Segment2)])).void }
        def initialize(type:, url:, start_time: nil, end_time: nil, intro_url: nil, outro_url: nil, expunge_segments: nil, segments: nil)
          @type = type
          @url = url
          @start_time = start_time
          @end_time = end_time
          @intro_url = intro_url
          @outro_url = outro_url
          @expunge_segments = expunge_segments
          @segments = segments
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @url == other.url
          return false unless @start_time == other.start_time
          return false unless @end_time == other.end_time
          return false unless @intro_url == other.intro_url
          return false unless @outro_url == other.outro_url
          return false unless @expunge_segments == other.expunge_segments
          return false unless @segments == other.segments
          true
        end
      end
    end
  end
end
