# typed: true
# frozen_string_literal: true


class FastpixApiSDK::Models::Components::Views
  extend ::Crystalline::MetadataFields::ClassMethods
end


class FastpixApiSDK::Models::Components::Views
  def workspace_id(); end
  def workspace_id=(str_); end
  def events(); end
  def events=(str_); end
  def exit_before_video_start(); end
  def exit_before_video_start=(str_); end
  def experiment_name(); end
  def experiment_name=(str_); end
  def insert_timestamp(); end
  def insert_timestamp=(str_); end
  def player_autoplay_on(); end
  def player_autoplay_on=(str_); end
  def player_preload_on(); end
  def player_preload_on=(str_); end
  def player_remote_played(); end
  def player_remote_played=(str_); end
  def used_full_screen(); end
  def used_full_screen=(str_); end
  def video_startup_failed(); end
  def video_startup_failed=(str_); end
  def view_has_ad(); end
  def view_has_ad=(str_); end
  def view_id(); end
  def view_id=(str_); end
  def os_version(); end
  def os_version=(str_); end
  def asn_name(); end
  def asn_name=(str_); end
  def asn_id(); end
  def asn_id=(str_); end
  def media_id(); end
  def media_id=(str_); end
  def buffer_count(); end
  def buffer_count=(str_); end
  def buffer_fill(); end
  def buffer_fill=(str_); end
  def buffer_frequency(); end
  def buffer_frequency=(str_); end
  def cdn(); end
  def cdn=(str_); end
  def city(); end
  def city=(str_); end
  def continent(); end
  def continent=(str_); end
  def country_code(); end
  def country_code=(str_); end
  def country(); end
  def country=(str_); end
  def custom1(); end
  def custom1=(str_); end
  def custom2(); end
  def custom2=(str_); end
  def custom3(); end
  def custom3=(str_); end
  def custom4(); end
  def custom4=(str_); end
  def custom5(); end
  def custom5=(str_); end
  def custom6(); end
  def custom6=(str_); end
  def custom7(); end
  def custom7=(str_); end
  def custom8(); end
  def custom8=(str_); end
  def custom9(); end
  def custom9=(str_); end
  def custom10(); end
  def custom10=(str_); end
  def latitude(); end
  def latitude=(str_); end
  def fp_live_stream_id(); end
  def fp_live_stream_id=(str_); end
  def live_stream_latency(); end
  def live_stream_latency=(str_); end
  def longitude(); end
  def longitude=(str_); end
  def page_load_time(); end
  def page_load_time=(str_); end
  def page_context(); end
  def page_context=(str_); end
  def view_page_url(); end
  def view_page_url=(str_); end
  def fp_playback_id(); end
  def fp_playback_id=(str_); end
  def playback_score(); end
  def playback_score=(str_); end
  def error_code(); end
  def error_code=(str_); end
  def error_message(); end
  def error_message=(str_); end
  def player_height(); end
  def player_height=(str_); end
  def player_instance_id(); end
  def player_instance_id=(str_); end
  def player_language(); end
  def player_language=(str_); end
  def fp_sdk(); end
  def fp_sdk=(str_); end
  def fp_sdk_version(); end
  def fp_sdk_version=(str_); end
  def player_name(); end
  def player_name=(str_); end
  def player_poster(); end
  def player_poster=(str_); end
  def player_software_version(); end
  def player_software_version=(str_); end
  def player_software_name(); end
  def player_software_name=(str_); end
  def video_source_domain(); end
  def video_source_domain=(str_); end
  def video_source_duration(); end
  def video_source_duration=(str_); end
  def player_source_height(); end
  def player_source_height=(str_); end
  def video_source_hostname(); end
  def video_source_hostname=(str_); end
  def video_source_stream_type(); end
  def video_source_stream_type=(str_); end
  def video_source_type(); end
  def video_source_type=(str_); end
  def video_source_url(); end
  def video_source_url=(str_); end
  def player_source_width(); end
  def player_source_width=(str_); end
  def player_initialization_time(); end
  def player_initialization_time=(str_); end
  def player_version(); end
  def player_version=(str_); end
  def player_width(); end
  def player_width=(str_); end
  def render_quality_score(); end
  def render_quality_score=(str_); end
  def buffer_ratio(); end
  def buffer_ratio=(str_); end
  def stability_score(); end
  def stability_score=(str_); end
  def region(); end
  def region=(str_); end
  def session_id(); end
  def session_id=(str_); end
  def startup_score(); end
  def startup_score=(str_); end
  def sub_property_id(); end
  def sub_property_id=(str_); end
  def video_startup_time(); end
  def video_startup_time=(str_); end
  def updated_timestamp(); end
  def updated_timestamp=(str_); end
  def video_content_type(); end
  def video_content_type=(str_); end
  def video_duration(); end
  def video_duration=(str_); end
  def video_id(); end
  def video_id=(str_); end
  def video_language(); end
  def video_language=(str_); end
  def video_series(); end
  def video_series=(str_); end
  def video_title(); end
  def video_title=(str_); end
  def avg_request_latency(); end
  def avg_request_latency=(str_); end
  def avg_request_throughput(); end
  def avg_request_throughput=(str_); end
  def drm_type(); end
  def drm_type=(str_); end
  def dropped_frame_count(); end
  def dropped_frame_count=(str_); end
  def view_end(); end
  def view_end=(str_); end
  def max_downscaling(); end
  def max_downscaling=(str_); end
  def view_max_playhead_position(); end
  def view_max_playhead_position=(str_); end
  def max_request_latency(); end
  def max_request_latency=(str_); end
  def max_upscaling(); end
  def max_upscaling=(str_); end
  def view_playing_time(); end
  def view_playing_time=(str_); end
  def view_seeked_count(); end
  def view_seeked_count=(str_); end
  def view_seeked_duration(); end
  def view_seeked_duration=(str_); end
  def view_start(); end
  def view_start=(str_); end
  def view_total_content_playback_time(); end
  def view_total_content_playback_time=(str_); end
  def avg_downscaling(); end
  def avg_downscaling=(str_); end
  def avg_upscaling(); end
  def avg_upscaling=(str_); end
  def browser_name(); end
  def browser_name=(str_); end
  def browser_version(); end
  def browser_version=(str_); end
  def connectiontype(); end
  def connectiontype=(str_); end
  def device_type(); end
  def device_type=(str_); end
  def device_manufacturer(); end
  def device_manufacturer=(str_); end
  def device_model(); end
  def device_model=(str_); end
  def device_name(); end
  def device_name=(str_); end
  def quality_of_experience_score(); end
  def quality_of_experience_score=(str_); end
  def os_name(); end
  def os_name=(str_); end
  def user_agent(); end
  def user_agent=(str_); end
  def viewer_id(); end
  def viewer_id=(str_); end
  def total_watch_time(); end
  def total_watch_time=(str_); end
  def average_bitrate(); end
  def average_bitrate=(str_); end
  def jump_latency(); end
  def jump_latency=(str_); end
  def player_resolution(); end
  def player_resolution=(str_); end
  def video_resolution(); end
  def video_resolution=(str_); end
end