# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Components
    
      # WatermarkInputType - Type of overlay (currently only supports 'watermark').
      class WatermarkInputType < T::Enum
        enums do
          WATERMARK = new('watermark')
        end
      end
    end
  end
end
