# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module FastpixApiSDK
  module Models
    module Errors
      autoload :APIError, 'fastpix_api_sdk/models/errors/apierror.rb'
      autoload :BadRequestError, 'fastpix_api_sdk/models/errors/badrequest_error.rb'
      autoload :BadRequestErrorError, 'fastpix_api_sdk/models/errors/badrequest_error_error.rb'
      autoload :ForbiddenError, 'fastpix_api_sdk/models/errors/forbidden_error.rb'
      autoload :ForbiddenErrorError, 'fastpix_api_sdk/models/errors/forbidden_error_error.rb'
      autoload :InvalidPermissionError, 'fastpix_api_sdk/models/errors/invalidpermission_error.rb'
      autoload :InvalidPermissionErrorError, 'fastpix_api_sdk/models/errors/invalidpermission_error_error.rb'
      autoload :MediaNotFoundError, 'fastpix_api_sdk/models/errors/medianotfound_error.rb'
      autoload :MediaNotFoundErrorError, 'fastpix_api_sdk/models/errors/medianotfound_error_error.rb'
      autoload :MediaOrPlaybackNotFoundError, 'fastpix_api_sdk/models/errors/mediaorplaybacknotfound_error.rb'
      autoload :MediaOrPlaybackNotFoundErrorError, 'fastpix_api_sdk/models/errors/mediaorplaybacknotfound_error_error.rb'
      autoload :NotFoundError, 'fastpix_api_sdk/models/errors/notfounderror.rb'
      autoload :NotFoundErrorPlaybackId, 'fastpix_api_sdk/models/errors/notfounderrorplaybackid.rb'
      autoload :NotFoundErrorPlaybackIdError, 'fastpix_api_sdk/models/errors/notfounderrorplaybackid_error.rb'
      autoload :NotFoundErrorSimulcast, 'fastpix_api_sdk/models/errors/notfounderrorsimulcast.rb'
      autoload :NotFoundErrorSimulcastError, 'fastpix_api_sdk/models/errors/notfounderrorsimulcast_error.rb'
      autoload :NotFoundErrorError, 'fastpix_api_sdk/models/errors/notfounderror_error.rb'
      autoload :SimulcastUnavailableError, 'fastpix_api_sdk/models/errors/simulcastunavailable_error.rb'
      autoload :SimulcastUnavailableErrorError, 'fastpix_api_sdk/models/errors/simulcastunavailable_error_error.rb'
      autoload :UnauthorizedError, 'fastpix_api_sdk/models/errors/unauthorized_error.rb'
      autoload :UnauthorizedErrorError, 'fastpix_api_sdk/models/errors/unauthorized_error_error.rb'
      autoload :ValidationErrorResponse, 'fastpix_api_sdk/models/errors/validationerrorresponse.rb'
      autoload :ValidationErrorResponseError, 'fastpix_api_sdk/models/errors/validationerrorresponse_error.rb'
      autoload :Field, 'fastpix_api_sdk/models/errors/field.rb'
    end
  end
end
