# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Operations
    

      class CreateMediaPlaybackIdRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # When creating the media, FastPix assigns a universally unique identifier with a maximum length of 255 characters.
        field :media_id, ::String, { 'path_param': { 'field_name': 'mediaId', 'style': 'simple', 'explode': false } }
        # Request body for creating playback id for an media
        field :request_body, T.nilable(Models::Operations::CreateMediaPlaybackIdRequestBody), { 'request': { 'media_type': 'application/json' } }

        sig { params(media_id: ::String, request_body: T.nilable(Models::Operations::CreateMediaPlaybackIdRequestBody)).void }
        def initialize(media_id:, request_body: nil)
          @media_id = media_id
          @request_body = request_body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @media_id == other.media_id
          return false unless @request_body == other.request_body
          true
        end
      end
    end
  end
end
