# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Operations
    

      class DeleteMediaRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # When creating the media, FastPix assigns a universally unique identifier with a maximum length of 255 characters.
        field :media_id, ::String, { 'path_param': { 'field_name': 'mediaId', 'style': 'simple', 'explode': false } }

        sig { params(media_id: ::String).void }
        def initialize(media_id:)
          @media_id = media_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @media_id == other.media_id
          true
        end
      end
    end
  end
end
