# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Operations
    

      class DeletePlaybackIdOfStreamRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
        field :stream_id, ::String, { 'path_param': { 'field_name': 'streamId', 'style': 'simple', 'explode': false } }
        # Unique identifier for the playbackId
        field :playback_id, ::String, { 'query_param': { 'field_name': 'playbackId', 'style': 'form', 'explode': true } }

        sig { params(stream_id: ::String, playback_id: ::String).void }
        def initialize(stream_id:, playback_id:)
          @stream_id = stream_id
          @playback_id = playback_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @stream_id == other.stream_id
          return false unless @playback_id == other.playback_id
          true
        end
      end
    end
  end
end
