# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Operations
    
      # GetAllStreamsOrderBy - The list of value can be order in two ways DESC (Descending) or ASC (Ascending). In case not specified, by default it will be DESC.
      class GetAllStreamsOrderBy < T::Enum
        enums do
          ASC = new('asc')
          DESC = new('desc')
        end
      end
    end
  end
end
