# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Operations
    
      # LanguageCode - Language codes (BCP 47 compliant) used for text files.
      # 
      class LanguageCode < T::Enum
        enums do
          EN = new('en')
          IT = new('it')
          PL = new('pl')
          ES = new('es')
          FR = new('fr')
          RU = new('ru')
          NL = new('nl')
        end
      end
    end
  end
end
