# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Operations
    
      # Type - Defines the type of input. Possible values include video, audio, av.
      # 
      class Type < T::Enum
        enums do
          VIDEO = new('video')
          AUDIO = new('audio')
          AV = new('av')
        end
      end
    end
  end
end
