# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module FastpixApiSDK
  module Models
    module Operations
    

      class UpdateSpecificSimulcastOfStreamRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
        field :stream_id, ::String, { 'path_param': { 'field_name': 'streamId', 'style': 'simple', 'explode': false } }
        # When you create the new simulcast, FastPix assign a universal unique identifier which can contain a maximum of 255 characters.
        field :simulcast_id, ::String, { 'path_param': { 'field_name': 'simulcastId', 'style': 'simple', 'explode': false } }

        field :simulcast_update_request, T.nilable(Models::Components::SimulcastUpdateRequest), { 'request': { 'media_type': 'application/json' } }

        sig { params(stream_id: ::String, simulcast_id: ::String, simulcast_update_request: T.nilable(Models::Components::SimulcastUpdateRequest)).void }
        def initialize(stream_id:, simulcast_id:, simulcast_update_request: nil)
          @stream_id = stream_id
          @simulcast_id = simulcast_id
          @simulcast_update_request = simulcast_update_request
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @stream_id == other.stream_id
          return false unless @simulcast_id == other.simulcast_id
          return false unless @simulcast_update_request == other.simulcast_update_request
          true
        end
      end
    end
  end
end
