# Generated code for FastPix API SDK.

# typed: true
# frozen_string_literal: true


module FastpixClient
  module Models
    module Operations

      class ListVideoViewsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
        # 
        # **Accepted formats are:**
        # 
        # array of epoch timestamps for example  
        # `timespan[]=1498867200&timespan[]=1498953600`
        # 
        # duration string for example  
        # `timespan[]=24:hours` or `timespan[]=7:days`
        # 
        field :timespan, Crystalline::Nilable.new(Models::Operations::ListVideoViewsTimespan), { 'query_param': { 'field_name': 'timespan[]', 'style': 'form', 'explode': true } }
        # Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass "!" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
        # Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]
        # 
        field :filterby, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'filterby[]', 'style': 'form', 'explode': true } }
        # Pass the viewer_id to filter the list of views. This value can be manually set during integration or generated by FastPix. When set manually it can be a string of aplha numeric values of any length.
        # 
        field :viewer_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'viewerId', 'style': 'form', 'explode': true } }
        # Pass the limit to display only the rows specified by the value.
        # 
        field :limit, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Pass the offset value to indicate the page number.
        # 
        field :offset, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': true } }
        # Pass the error code to filter the list of views. The possible values of error code can be fetched from list of errors end point.
        # 
        field :error_code, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'errorCode', 'style': 'form', 'explode': true } }
        # Pass this value to sort the view list by.
        # 
        field :order_by, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'orderBy', 'style': 'form', 'explode': true } }
        # The order direction to sort the view list by.
        # 
        field :sort_order, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'sortOrder', 'style': 'form', 'explode': true } }

        sig { params(timespan: T.nilable(Models::Operations::ListVideoViewsTimespan), filterby: T.nilable(::String), viewer_id: T.nilable(::String), limit: T.nilable(::Integer), offset: T.nilable(::Integer), error_code: T.nilable(::String), order_by: T.nilable(::String), sort_order: T.nilable(::String)).void }
        def initialize(timespan: nil, filterby: nil, viewer_id: nil, limit: 10, offset: 1, error_code: nil, order_by: 'view_end', sort_order: 'asc')
          @timespan = timespan
          @filterby = filterby
          @viewer_id = viewer_id
          @limit = limit
          @offset = offset
          @error_code = error_code
          @order_by = order_by
          @sort_order = sort_order
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @timespan == other.timespan
          return false unless @filterby == other.filterby
          return false unless @viewer_id == other.viewer_id
          return false unless @limit == other.limit
          return false unless @offset == other.offset
          return false unless @error_code == other.error_code
          return false unless @order_by == other.order_by
          return false unless @sort_order == other.sort_order
          true
        end
      end
    end
  end
end
