# Generated code for FastPix API SDK.

# typed: true
# frozen_string_literal: true


module FastpixClient
  module Models
    module Components
      # A collection of Playback ID objects utilized for crafting HLS playback urls.
      class CreatePlaybackId
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier is generated by FastPix for the playbacks.
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('id') } }
        # Access policy for media content
        field :access_policy, Crystalline::Nilable.new(Models::Components::AccessPolicy), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('accessPolicy'), 'decoder': Utils.enum_from_string(Models::Components::AccessPolicy, true) } }
        # Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
        field :access_restrictions, Crystalline::Nilable.new(Models::Components::CreatePlaybackIdAccessRestrictions), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('accessRestrictions') } }
        # The maximum resolution for the playback ID.
        field :resolution, Crystalline::Nilable.new(Models::Components::Resolution), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('resolution'), 'decoder': Utils.enum_from_string(Models::Components::Resolution, true) } }

        sig { params(id: T.nilable(::String), access_policy: T.nilable(Models::Components::AccessPolicy), access_restrictions: T.nilable(Models::Components::CreatePlaybackIdAccessRestrictions), resolution: T.nilable(Models::Components::Resolution)).void }
        def initialize(id: nil, access_policy: nil, access_restrictions: nil, resolution: nil)
          @id = id
          @access_policy = access_policy
          @access_restrictions = access_restrictions
          @resolution = resolution
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @access_policy == other.access_policy
          return false unless @access_restrictions == other.access_restrictions
          return false unless @resolution == other.resolution
          true
        end
      end
    end
  end
end
