# Generated code for FastPix API SDK.

# typed: true
# frozen_string_literal: true


module FastpixClient
  module Models
    module Components

      class LiveMediaClips
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier assigned to the media when created. The value must be a valid UUID.
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('id') } }
        # A unique identifier is generated by FastPix for the workspace.
        field :workspace_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('workspaceId') } }
        # The ID of the livestream for which the clips were created.
        field :stream_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('streamId') } }
        # The unique identifier of the user who created this media.
        field :creator_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('creatorId') } }
        # Determines the media's status, which can be one of the possible values.
        field :status, Crystalline::Nilable.new(Models::Components::LiveMediaClipsStatus), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Components::LiveMediaClipsStatus, true) } }
        # The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it.
        field :source_access, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('sourceAccess') } }
        # A collection of Playback ID objects utilized for crafting HLS playback URLs.
        field :playback_ids, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::PlaybackId)), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('playbackIds') } }
        # A media consists of different media tracks, like video, audio, and subtitle, all combined.
        field :tracks, Crystalline::Nilable.new(Crystalline::Array.new(Crystalline::Union.new(Models::Components::VideoTrack, Models::Components::AudioTrack, Models::Components::SubtitleTrack))), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('tracks') } }
        # The MP4 renditions generated for the media. Present only when MP4 support is enabled.
        field :mp4_support, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::LiveMediaClipsMp4Support)), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('mp4Support') } }
        # The length of the media in seconds, with a maximum allowed duration of 12 hours per individual media.
        field :duration, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('duration') } }
        # Time the media was created, defined as a localDateTime (UTC Time).
        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('createdAt'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # Time the media was updated, defined as a localDateTime (UTC Time).
        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('updatedAt'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # A video thumbnail is a still image that acts as the preview image for your video.
        field :thumbnail, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('thumbnail') } }
        # Title of the media file.
        field :title, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('title') } }
        # The maximum resolution specified by the user for the media.
        field :max_resolution, Crystalline::Nilable.new(Models::Components::LiveMediaClipsMaxResolution), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('maxResolution'), 'decoder': Utils.enum_from_string(Models::Components::LiveMediaClipsMaxResolution, true) } }
        # The actual resolution of the uploaded media. This represents the native quality of the source media.
        field :source_resolution, Crystalline::Nilable.new(Models::Components::LiveMediaClipsSourceResolution), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('sourceResolution'), 'decoder': Utils.enum_from_string(Models::Components::LiveMediaClipsSourceResolution, true) } }
        # List of generated subtitle tracks associated with the media.
        field :generated_subtitles, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::TracksSubtitles)), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('generatedSubtitles') } }
        # Indicates whether the media contains only audio (no video track).
        field :is_audio_only, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('isAudioOnly') } }
        # Indicates whether subtitles are available for the media.
        field :subtitle_available, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('subtitleAvailable') } }
        # The aspect ratio of a video is a value that describes the relative shape of a video based on its width and height.
        field :aspect_ratio, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('aspectRatio') } }

        sig { params(id: T.nilable(::String), workspace_id: T.nilable(::String), stream_id: T.nilable(::String), creator_id: T.nilable(::String), status: T.nilable(Models::Components::LiveMediaClipsStatus), source_access: T.nilable(T::Boolean), playback_ids: T.nilable(T::Array[Models::Components::PlaybackId]), tracks: T.nilable(T::Array[T.any(Models::Components::VideoTrack, Models::Components::AudioTrack, Models::Components::SubtitleTrack)]), mp4_support: T.nilable(T::Array[Models::Components::LiveMediaClipsMp4Support]), duration: T.nilable(::String), created_at: T.nilable(::DateTime), updated_at: T.nilable(::DateTime), thumbnail: T.nilable(::String), title: T.nilable(::String), max_resolution: T.nilable(Models::Components::LiveMediaClipsMaxResolution), source_resolution: T.nilable(Models::Components::LiveMediaClipsSourceResolution), generated_subtitles: T.nilable(T::Array[Models::Components::TracksSubtitles]), is_audio_only: T.nilable(T::Boolean), subtitle_available: T.nilable(T::Boolean), aspect_ratio: T.nilable(::String)).void }
        def initialize(id: nil, workspace_id: nil, stream_id: nil, creator_id: nil, status: nil, source_access: nil, playback_ids: nil, tracks: nil, mp4_support: nil, duration: nil, created_at: nil, updated_at: nil, thumbnail: nil, title: nil, max_resolution: Models::Components::LiveMediaClipsMaxResolution::ONE_THOUSAND_AND_EIGHTYP, source_resolution: Models::Components::LiveMediaClipsSourceResolution::ONE_THOUSAND_AND_EIGHTYP, generated_subtitles: nil, is_audio_only: nil, subtitle_available: nil, aspect_ratio: nil)
          @id = id
          @workspace_id = workspace_id
          @stream_id = stream_id
          @creator_id = creator_id
          @status = status
          @source_access = source_access
          @playback_ids = playback_ids
          @tracks = tracks
          @mp4_support = mp4_support
          @duration = duration
          @created_at = created_at
          @updated_at = updated_at
          @thumbnail = thumbnail
          @title = title
          @max_resolution = max_resolution
          @source_resolution = source_resolution
          @generated_subtitles = generated_subtitles
          @is_audio_only = is_audio_only
          @subtitle_available = subtitle_available
          @aspect_ratio = aspect_ratio
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class

          [@id, @workspace_id, @stream_id, @creator_id, @status,
           @source_access, @playback_ids, @tracks, @mp4_support, @duration,
           @created_at, @updated_at, @thumbnail, @title, @max_resolution,
           @source_resolution, @generated_subtitles, @is_audio_only, @subtitle_available, @aspect_ratio] ==
            [other.id, other.workspace_id, other.stream_id, other.creator_id, other.status,
             other.source_access, other.playback_ids, other.tracks, other.mp4_support, other.duration,
             other.created_at, other.updated_at, other.thumbnail, other.title, other.max_resolution,
             other.source_resolution, other.generated_subtitles, other.is_audio_only, other.subtitle_available, other.aspect_ratio]
        end
      end
    end
  end
end
