# Generated code for FastPix API SDK.

# typed: true
# frozen_string_literal: true


module FastpixClient
  module Models
    module Components

      class SourceAccessMedia
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier assigned to the media when created. The value must be a valid UUID.
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('id') } }
        # A unique identifier is generated by FastPix for the workspace.
        field :workspace_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('workspaceId') } }
        # The quality tier applied to the media.
        field :media_quality, Crystalline::Nilable.new(Models::Components::SourceAccessMediaMediaQuality), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('mediaQuality'), 'decoder': Utils.enum_from_string(Models::Components::SourceAccessMediaMediaQuality, true) } }
        # The unique identifier of the user who created this media.
        field :creator_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('creatorId') } }
        # Determines the media's status, which can be one of the possible values.
        field :status, Crystalline::Nilable.new(Models::Components::SourceAccessMediaStatus), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Components::SourceAccessMediaStatus, true) } }
        # The MP4 renditions generated for the media. Present only when MP4 support is enabled.
        field :mp4_support, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::SourceAccessMediaMp4Support)), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('mp4Support') } }
        # A collection of Playback ID objects utilized for crafting HLS playback URLs.
        field :playback_ids, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::PlaybackId)), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('playbackIds') } }
        # A media consists of different media tracks, like video, audio, and subtitle, all combined.
        field :tracks, Crystalline::Nilable.new(Crystalline::Array.new(Crystalline::Union.new(Models::Components::VideoTrack, Models::Components::AudioTrack, Models::Components::SubtitleTrack))), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('tracks') } }
        # Represents an AI response record containing status and data for AI-generated features like summary, chapters, named entities, or moderation.
        field :summary, Crystalline::Nilable.new(Models::Components::AiSummaryRecord), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('summary') } }
        # Represents an AI response record containing status and data for AI-generated features like summary, chapters, named entities, or moderation.
        field :chapters, Crystalline::Nilable.new(Models::Components::AiResponseRecord), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('chapters') } }
        # Represents an AI response record containing status and data for AI-generated features like summary, chapters, named entities, or moderation.
        field :named_entities, Crystalline::Nilable.new(Models::Components::AiResponseRecord), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('namedEntities') } }
        # Represents an AI response record containing status and data for AI-generated features like summary, chapters, named entities, or moderation.
        field :moderation, Crystalline::Nilable.new(Models::Components::AiResponseRecord), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('moderation') } }
        # The length of the media in seconds, with a maximum allowed duration of 12 hours per individual media.
        field :duration, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('duration') } }
        # Time the media was created, defined as a localDateTime (UTC Time).
        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('createdAt'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # Time the media was updated, defined as a localDateTime (UTC Time).
        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('updatedAt'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # A video thumbnail is a still image that acts as the preview image for your video.
        field :thumbnail, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('thumbnail') } }
        # You can search for videos with specific key value pairs using metadata, when you tag a video in "key" : "value" pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
        # 
        field :metadata, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::String)), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('metadata') } }
        # Title of the media file.
        field :title, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('title') } }
        # The maximum resolution specified by the user for the media.
        field :max_resolution, Crystalline::Nilable.new(Models::Components::SourceAccessMediaMaxResolution), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('maxResolution'), 'decoder': Utils.enum_from_string(Models::Components::SourceAccessMediaMaxResolution, true) } }
        # The actual resolution of the uploaded media. This represents the native quality of the source media.
        field :source_resolution, Crystalline::Nilable.new(Models::Components::SourceAccessMediaSourceResolution), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('sourceResolution'), 'decoder': Utils.enum_from_string(Models::Components::SourceAccessMediaSourceResolution, true) } }
        # The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it.
        field :source_access, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('sourceAccess') } }
        # List of generated subtitle tracks associated with the media.
        field :generated_subtitles, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::TracksSubtitles)), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('generatedSubtitles') } }
        # Indicates whether the media contains only audio (no video track).
        field :is_audio_only, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('isAudioOnly') } }
        # Indicates whether subtitles are available for the media.
        field :subtitle_available, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('subtitleAvailable') } }
        # Enhance the quality and volume of the audio track. This is available for pre-recorded content only.
        field :optimize_audio, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('optimizeAudio') } }
        # The aspect ratio of a video describes its shape based on the relationship between its width and height.
        field :aspect_ratio, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::FastpixClient::Utils.field_name('aspectRatio') } }

        sig { params(id: T.nilable(::String), workspace_id: T.nilable(::String), media_quality: T.nilable(Models::Components::SourceAccessMediaMediaQuality), creator_id: T.nilable(::String), status: T.nilable(Models::Components::SourceAccessMediaStatus), mp4_support: T.nilable(T::Array[Models::Components::SourceAccessMediaMp4Support]), playback_ids: T.nilable(T::Array[Models::Components::PlaybackId]), tracks: T.nilable(T::Array[T.any(Models::Components::VideoTrack, Models::Components::AudioTrack, Models::Components::SubtitleTrack)]), summary: T.nilable(Models::Components::AiSummaryRecord), chapters: T.nilable(Models::Components::AiResponseRecord), named_entities: T.nilable(Models::Components::AiResponseRecord), moderation: T.nilable(Models::Components::AiResponseRecord), duration: T.nilable(::String), created_at: T.nilable(::DateTime), updated_at: T.nilable(::DateTime), thumbnail: T.nilable(::String), metadata: T.nilable(T::Hash[Symbol, ::String]), title: T.nilable(::String), max_resolution: T.nilable(Models::Components::SourceAccessMediaMaxResolution), source_resolution: T.nilable(Models::Components::SourceAccessMediaSourceResolution), source_access: T.nilable(T::Boolean), generated_subtitles: T.nilable(T::Array[Models::Components::TracksSubtitles]), is_audio_only: T.nilable(T::Boolean), subtitle_available: T.nilable(T::Boolean), optimize_audio: T.nilable(T::Boolean), aspect_ratio: T.nilable(::String)).void }
        def initialize(id: nil, workspace_id: nil, media_quality: nil, creator_id: nil, status: nil, mp4_support: nil, playback_ids: nil, tracks: nil, summary: nil, chapters: nil, named_entities: nil, moderation: nil, duration: nil, created_at: nil, updated_at: nil, thumbnail: nil, metadata: nil, title: nil, max_resolution: Models::Components::SourceAccessMediaMaxResolution::ONE_THOUSAND_AND_EIGHTYP, source_resolution: Models::Components::SourceAccessMediaSourceResolution::ONE_THOUSAND_AND_EIGHTYP, source_access: nil, generated_subtitles: nil, is_audio_only: nil, subtitle_available: nil, optimize_audio: nil, aspect_ratio: nil)
          @id = id
          @workspace_id = workspace_id
          @media_quality = media_quality
          @creator_id = creator_id
          @status = status
          @mp4_support = mp4_support
          @playback_ids = playback_ids
          @tracks = tracks
          @summary = summary
          @chapters = chapters
          @named_entities = named_entities
          @moderation = moderation
          @duration = duration
          @created_at = created_at
          @updated_at = updated_at
          @thumbnail = thumbnail
          @metadata = metadata
          @title = title
          @max_resolution = max_resolution
          @source_resolution = source_resolution
          @source_access = source_access
          @generated_subtitles = generated_subtitles
          @is_audio_only = is_audio_only
          @subtitle_available = subtitle_available
          @optimize_audio = optimize_audio
          @aspect_ratio = aspect_ratio
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class

          [@id, @workspace_id, @media_quality, @creator_id, @status,
           @mp4_support, @playback_ids, @tracks, @summary, @chapters,
           @named_entities, @moderation, @duration, @created_at, @updated_at,
           @thumbnail, @metadata, @title, @max_resolution, @source_resolution,
           @source_access, @generated_subtitles, @is_audio_only, @subtitle_available, @optimize_audio, @aspect_ratio] ==
            [other.id, other.workspace_id, other.media_quality, other.creator_id, other.status,
             other.mp4_support, other.playback_ids, other.tracks, other.summary, other.chapters,
             other.named_entities, other.moderation, other.duration, other.created_at, other.updated_at,
             other.thumbnail, other.metadata, other.title, other.max_resolution, other.source_resolution,
             other.source_access, other.generated_subtitles, other.is_audio_only, other.subtitle_available, other.optimize_audio, other.aspect_ratio]
        end
      end
    end
  end
end
